---
- hosts: nginxservers
  become: True
  tasks:
    - name: Install Nginx latest version
      apt: 
        name: "nginx" 
        state: "latest"
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
